;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-delete-forward
	c-electric-semi&comma
	ian/format-code
	kill-region
	))

(setq mc/cmds-to-run-once
      '(
	org-self-insert-command
	))
