;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	duplicate-line
	helm-occur
	ian/format-code
	kill-region
	mark-sexp
	zap-up-to-char
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-slash
	org-delete-char
	org-self-insert-command
	))
