#+TITLE: NEmacs - NateNateNate's Emacs Config
#+AUTHOR: NateNateNate
#+STARTUP: overview
#+OPTIONS: num:nil
#+EMAIL: natenatenat3@protonmail.com

* Usage Disclaimer
You probably shouldn't use this configuration.

This Emacs configuration is provided as-is, and its functionality is intended for personal use. While I've made efforts to ensure its reliability,
please be aware of the following:

- I suck at Emacs Lisp, so there could be limitations, bugs, or performance issues.
- I also suck at [[https://en.wikipedia.org/wiki/Free_and_open-source_software#:~:text=Free%20and%20open%2Dsource%20software%20(FOSS)%20is%20a%20term,are%20encouraged%20to%20improve%20the][FOSS]].
- This configuration might not be suitable for all use cases, and its behavior may change over time.
- I may not be able to provide immediate or comprehensive support in case of issues or feature requests.

If you encounter any problems or have suggestions for improvements, feel free to report them by creating an issue.

By using my configuration, you agree to do so at your own discretion and understand that there may be limitations.

Also, please read the [[./LICENSE.txt][LICENSE]].

* Language Support
Emacs provides built-in language support for many languages, thankfully. The languages listed here are just the languages that
I'll work in often. Emacs may/not support languages that aren't mentioned in this list.

- [X] C/CPP
- [X] Zig
- [X] Rust
- [X] Julia (I did this for you, Aizzat!)
- [X] Clojure
- [X] Common Lisp
- [X] Scheme
- [X] PHP
- [X] JS/TS
- [X] Python
- [X] Bash
- [X] CSS
- [X] HTML/Markdown/YAML

I don't write in Go often, and haven't written in it in a few months. If I ever need to, I'll set it up. I'm just lazy today.

** LSP
We need to install a few things so that LSP works fine.

#+begin_src bash
  sudo npm i -g intellephense
  pip3 install pylsp
  sudo npm i -g typescript-language-server
#+end_src

I used =clangd= as the LSP for C/CPP which are the languages I write in a lot, therefore I've prioritized support for these languages. 

* OS Support
Tested on MacOS and Gnu operating systems like Debian and Ubuntu. I'm not certain of whether it works with Windows.
At a glance, it should work just fine. However, I wouldn't know as I don't use Windows (because its trash).

* Keybindings
The list of keybindings or remaps that I can recall.

| Kbd     | Function                      |
| =s-1=     | devdocs-lookup                |
| =C-c r=   | nemacs/config-reload          |
| =C-c e=   | nemacs/config-visit           |
| =C-c f=   | nemacs/toggle-maximize-buffer |
| =C-c z >= | eradio-play                   |
| =C-c z <= | eradio-stop                   |
| =C-c z -= | eradio-toggle                 |
| =C-x g=   | magit-status                  |
| =M-o=     | ace-window                    |
| =M-O=     | ace-swap-window               |
| C-=     | er/expand-region              |
| =M-+=     | helm-themes                   |
| =C-c b=   | switch-to-buffer              |
| =M-y=     | helm-show-kill-ring           |
| =M-n=     | avy-goto-char                 |
| =M-?=     | Mark paragraph                |
| =C-c M-p= | find-file-at-point            |
| =C-c m=   | delete pair                   |
| =C-x C-.= | align-regexp                  |
| =C-c h=   | compile                       |
| =C-c c=   | imenu                         |
| =M-Z=     | zap-up-to-char                |
| =C-c d=   | duplicate-line                |
| =C-cl=    | org-store-link                |
| =C-ca=    | org-agenda                    |
| =M-p=     | ian/format-code               |

* ENV
Create an =environment-variables= directory in the root, and a file called =custom-env.el=.
Add these values in:

#+begin_src emacs-lisp
  ;; custom-env.el

  (setenv "EMACS_CONFIG_PATH" "")
  (setenv "EMACS_BACKUP_DIR" "")
  (setenv "EMACS_TRASH_DIR" "")
  (setenv "EMACS_USERNAME" "")
  (setenv "EMACS_EMAIL" "")
  (setenv "HOME_DIR" "")
  (setenv "TS_SERVER_PATH" "")

  (provide 'custom-env)
#+end_src

* Themes
- doom-themes
- kaolin-themes
- color-theme-sanityinc-tomorrow
- ef-themes
- standard-themes
- naysayer-theme
- gruber-darker-theme
- solarized-theme
- color-theme-sanityinc-solarized
- jbeans-theme
- jetbrains-darcula-theme
- badwolf-theme
- lorissan (personal favorite)

* Handling Updates
If you decide to use this configuration (you shouldn't!), you'll have to update the configuration by running =git pull= and then run
=M-x <RET> package-list-packages=, followed by =u= and =x=.
